var clubs=[],curc=0,sData={},data={},curtactic=0,curplchange=0,curtacchange=0,plid=-1,plfrom=-1,plto=-1,plunder=-1,sh1=0,sh2=15,save=!1,settc=!1,arrOn=!1,opekanum="",numbercolor="blue",curbknum=0,zamnum=9,rep=[],sygpl=0,sygdf=0,curfl=0,cursk="#",wsize=768,xpx=0,xpy=0,imgPl="system/img/forms/dfFFFFFF.png",imgGK="system/img/forms/dfE08000.png",sel="",simb={stda:'<img width="12px" src="system/img/sostav/tick.gif">',stdo:'<img width="12px" src="system/img/sostav/tick.gif">'},nms=["Xуд C DF","Xуд C Mid",
"Xуд FW"],nmsdel=["LR DF","C DF","LR Mid","C Mid","FW"],nmsoops=["проход","не проход","ЖК","без ЖК"],nmsstda=["","[стдА-]","[стдА+]"],nmsstdo=["","[стдО-]","[стдО+]"],chead={},po=0,ds=0,roles=[{sn:"--",name:""},{sn:"Вр",name:"Вратарь"},{sn:"ВЧ",name:"Вратарь чистильщик",info:"Активно играет вне штрафной страхуя защитников"},{sn:"Лб",name:"Либеро"},{sn:"Дп",name:"Диспетчер",num:1,info:"Развивает атаки (только 1 на поле)"},{sn:"КЗ",name:"Крайний защитник"},{sn:"АЗ",name:"Атакующий защитник",info:"Чаще подключается в атаку"},
{sn:"Лт",name:"Латераль",info:"Играет по всему флангу"},{sn:"ЦЗ",name:"Центральный защитник"},{sn:"ВЗ",name:"Ведущий защитник",num:1,info:"Организует оборону с более слабыми партнерами (только 1 на поле)"},{sn:"ПО",name:"Персональщик",num:1,info:"Опекает выбранного игрока (только 1 на поле)"},{sn:"КП",name:"Крайний полузащитник",info:"Чаще или реже подключается в атаку"},{sn:"ОП",name:"Опорный полузащитник"},{sn:"ББ",name:"Бокс-ту-бокс",info:"работает по всему полю"},{sn:"ОБ",name:"Оборонительный полузащитник",
info:"Реже подключается"},{sn:"АП",name:"Атакующий полузащитник",info:"Чаще подключается в атаку"},{sn:"Ин",name:"Инсайд",info:"Cмещается ближе к центру"},{sn:"ЦП",name:"Центральный полузащитник",info:"Реже подключается"},{sn:"СХ",name:"Свободный художник",info:"Действует на свое усмотрение"},{sn:"Вн",name:"Вингер",info:"Нацелен на вход в штрафную"},{sn:"ОН",name:"Оттянутый нападающий",info:"Нацелен на вход в штрафную, опускается в глубину в поисках мяча"},{sn:"Нп",name:"Нападающий"},{sn:"Ст",name:"Столб",
info:"Скидывает мячи партнерам"},{sn:"Нг",name:"На грани",info:"Действует на грани офсайда"},{sn:"Нк",name:"Наконечник",info:"Старается завершать атаки при первой возможности"}],zads=[];zads[99]={sn:"--",name:""};zads[0]={sn:"-",name:""};zads[1]={sn:"Об",name:"Обыгрывать (чаще)",pm:1};zads[2]={sn:"Об",name:"Обыгрывать (реже)",pm:0};zads[3]={sn:"ДУ",name:"Бить издали (чаще)",pm:1};zads[4]={sn:"ДУ",name:"Бить издали (реже)",pm:0};zads[5]={sn:"Нв",name:"Навешивать (чаще)",pm:1};
zads[6]={sn:"Нв",name:"Навешивать (реже)",pm:0};zads[7]={sn:"Пр",name:"Простреливать (чаще)",pm:1};zads[8]={sn:"Пр",name:"Простреливать (реже)",pm:0};zads[9]={sn:"Пс",name:"Обостряющих передач (больше)",pm:1};zads[10]={sn:"Пс",name:"Обостряющих передач (меньше)",pm:0};zads[11]={sn:"Вх",name:"Играть на выходах (чаще)",pm:1};zads[12]={sn:"Вх",name:"Играть на выходах (реже)",pm:0};zads[13]={sn:"Мф",name:"Меняться флангами",pm:1};zads[14]={sn:"Дм",name:"Держать мяч",pm:1};
var poses=[{name:""},{name:"GK",def:1,roles:[2],zads:[11,12]},{name:"C SW",y:5,x:2,def:3,roles:[4],zads:[1,2,3,4,5,6,7,8,9,10]},{name:"L DF",y:4,x:0,def:5,roles:[6,7,10],zads:[1,2,3,4,5,6,7,8,9,10,13]},{name:"Cl DF",y:4,x:1,def:8,roles:[4,9,10],zads:[1,2,3,4,5,6,7,8,9,10]},{name:"Cc DF",y:4,x:2,def:8,roles:[4,9,10],zads:[1,2,3,4,5,6,7,8,9,10]},{name:"Cr DF",y:4,x:3,def:8,roles:[4,9,10],zads:[1,2,3,4,5,6,7,8,9,10]},{name:"R DF",y:4,x:4,def:5,roles:[6,7,10],zads:[1,2,3,4,5,6,7,8,9,10,13]},{name:"L DM",
y:3,x:0,def:14,roles:[7,10,11],zads:[1,2,3,4,5,6,7,8,9,10,13,14]},{name:"Cl DM",y:3,x:1,def:12,roles:[4,10,13],zads:[1,2,3,4,5,6,7,8,9,10,14]},{name:"Cc DM",y:3,x:2,def:12,roles:[4,10,13],zads:[1,2,3,4,5,6,7,8,9,10,14]},{name:"Cr DM",y:3,x:3,def:12,roles:[4,10,13],zads:[1,2,3,4,5,6,7,8,9,10,14]},{name:"R DM",y:3,x:4,def:14,roles:[7,10,11],zads:[1,2,3,4,5,6,7,8,9,10,13,14]},{name:"L MF",y:2,x:0,def:11,roles:[7,14,15,16],zads:[1,2,3,4,5,6,7,8,9,10,13,14]},{name:"Cl MF",y:2,x:1,def:17,roles:[4,10,13,
14,15,18],zads:[1,2,3,4,5,6,7,8,9,10,14]},{name:"Cc MF",y:2,x:2,def:17,roles:[4,10,13,14,15,18],zads:[1,2,3,4,5,6,7,8,9,10,14]},{name:"Cr MF",y:2,x:3,def:17,roles:[4,10,13,14,15,18],zads:[1,2,3,4,5,6,7,8,9,10,14]},{name:"R MF",y:2,x:4,def:11,roles:[7,14,15,16],zads:[1,2,3,4,5,6,7,8,9,10,13,14]},{name:"L AM",y:1,x:0,def:15,roles:[16,18,19],zads:[1,2,3,4,5,6,7,8,9,10,13,14]},{name:"Cl AM",y:1,x:1,def:15,roles:[4,18,20],zads:[1,2,3,4,5,6,7,8,9,10,14]},{name:"Cc AM",y:1,x:2,def:15,roles:[4,18,20],zads:[1,
2,3,4,5,6,7,8,9,10,14]},{name:"Cr AM",y:1,x:3,def:15,roles:[4,18,20],zads:[1,2,3,4,5,6,7,8,9,10,14]},{name:"R AM",y:1,x:4,def:15,roles:[16,18,19],zads:[1,2,3,4,5,6,7,8,9,10,13,14]},{name:"Cl FW",y:0,x:1,def:21,roles:[18,20,22,23,24],zads:[1,2,3,4,5,6,7,8,9,10,14]},{name:"Cc FW",y:0,x:2,def:21,roles:[18,20,22,23,24],zads:[1,2,3,4,5,6,7,8,9,10,14]},{name:"Cr FW",y:0,x:3,def:21,roles:[18,20,22,23,24],zads:[1,2,3,4,5,6,7,8,9,10,14]}];
poses[52]={name:"Фланг",y:2,x:0,def:14,roles:[7,10,11,15,16,18,19],zads:[1,2,3,4,5,6,7,8,9,10,13,14]};poses[53]={name:"Центр",y:2,x:2,def:12,roles:[4,10,13,14,15,18,20],zads:[1,2,3,4,5,6,7,8,9,10,14]};
var tacNames={pass:"Короткие Короткие Короткие Смешанные Смешанные Смешанные Длинные Длинные Длинные".split(" "),impro:"Редко Редко Редко Средне Средне Средне Часто Часто Часто".split(" "),temp:"Низкий Низкий Низкий Средний Средний Средний Высокий Высокий Высокий".split(" "),aggress:"Низкая Низкая Низкая Нормальная Нормальная Нормальная Высокая Высокая Высокая".split(" "),ward:"Неплотно Неплотно Неплотно Средне Средне Средне Плотно Плотно Плотно".split(" "),defline:"Глубоко Глубоко Глубоко Средне Средне Средне Высоко Высоко Высоко".split(" "),
defwidth:"Узко Узко Узко Средне Средне Средне Широко Широко Широко".split(" "),attwidth:"Узко Узко Узко Средне Средне Средне Широко Широко Широко".split(" ")},schetNames=["Меньше","Равен","Больше"],schetNamesShort=["<","=",">"];
function Init(){if(void 0===a){var a=a||{};a.stringify=a.stringify||function(b){var c,e,d;e=typeof b;var g=[],f=b&&b.constructor==Array;if("object"!=d||null===b)"string"==d&&(b='"'+b+'"'),e=String(b);else{for(c in b)e=b[c],d=typeof e,"string"==d?e='"'+e+'"':"object"==d&&null!==e&&(e=a.stringify(e)),g.push((f?"":'"'+c+'":')+String(e));e=(f?"[":"{")+String(g)+(f?"]":"}")}return e}}xpx=parseInt($("#pole-all").css("width"),10)/5;ypx=parseInt($(".pole:eq(1)").css("height"),10);wsize=parseInt($("table#main2").width(),
10);isNaN(wsize)&&(wsize=parseInt($("body").attr("data-size"),10));$(".pole").sortable({connectWith:".pole:not(.nomove),#pos1",handle:".player-img:not(.GK),.player-info:not(.GK),.player-number:not(.GK)",placeholder:"player-placeholder",tolerance:"intersect",delay:50,start:function(b,a){plid=parseInt(a.item.attr("id").replace("pl",""),10);plfrom=parseInt(a.item.parent().attr("id").replace("pos",""),10);freeArrow(plid)},sort:function(b,a){var e=parseInt(a.placeholder.parent().attr("id").replace("pos",
""),10);e!=plto&&(plto=e,arrOn&&(plto!=plfrom?drawArrow(plid,plto,0):freeArrow(plid)))},stop:function(b,a){if(arrOn)plfrom!=plto&&1!=plto?changePlData(plid,"posm",plto,curtactic):changePlData(plid,"posm",0,curtactic);else{if(plto!=plfrom){if(1<$("#pos"+plto+" .player").length){var e=parseInt($("#pos"+plto+" .player:not(#pl"+plid+")").attr("id").replace("pl",""),10);changePlData(e,"posm",0,curtactic);changePlData(e,"pos",plfrom,curtactic)}changePlData(plid,"pos",plto,curtactic)}0<data["sostav"+curtactic][plid].posm&&
changePlData(plid,"posm",0,curtactic)}void 0!=$("#pl"+plid).attr("style")&&$("#pl"+plid).removeAttr("style");plunder=plto=plfrom=plid=-1}}).disableSelection();$("#tabs").tabs({activate:function(a,c){if("tabs-5"==c.newPanel.attr("id")){$("#obzor").text("");var e,d,g,f,h,k;d={};h=["",!0];k="";g="<br><b>Смены тактик</b>:";f="<br><b>Замены игроков</b>:";var l="<br><b>Капитаны</b>:<br>",n="<br><b>Подача угловых</b>:<br>",q="<br><b>Штрафные удар</b>:<br>",m="<br><b>Штрафные навес</b>:<br>",r="<br><b>Пенальтисты</b>:<br>",
t=!1,u=!1,v=!1,w=!1,x=!1;for(e=1;9>=e;e++){d=data["tchange"+e];if(1==d.time[0]||1==d.schet[0]||1==d.oops[0]||1==d.del[0])h[d.tactic]=!0,g+="<br>",1==d.time[0]&&(g+="(мин:"+d.time[1]+"-"+d.time[2]+")"),1==d.schet[0]&&(g+="(счёт"+schetNamesShort[d.schet[1]]+(parseInt(d.schet[2],10)-4)+")"),1==d.del[0]&&(g+="(КК "+nmsdel[d.del[1]]+")"),1==d.oops[0]&&(g+="("+nmsoops[d.oops[1]]+")"),g+=" переход => Тактика "+d.tactic+(1==d.half?" [только установку]":"");d=data["pchange"+e];if(1==d.time[0]||1==d.schet[0]||
1==d.mark[0]||1==d.form[0]||1==d.oops[0]||1==d.del[0])f+="<br>",1==d.time[0]&&(f+="(мин:"+d.time[1]+"-"+d.time[2]+")"),1==d.mark[0]&&(f+="(оцн<"+(parseInt(d.mark[1],10)/10+5)+")"),1==d.form[0]&&(f+="(фор<"+(parseInt(d.form[1],10)+70)+")"),1==d.schet[0]&&(f+="(счёт"+schetNamesShort[d.schet[1]]+(parseInt(d.schet[2],10)-4)+")"),1==d.del[0]&&(f+="(КК "+nmsdel[d.del[1]]+")"),1==d.oops[0]&&(f+="("+nmsoops[d.oops[1]]+")"),f+=" замена "+(11<d.from?nms[parseInt(d.from,10)-12]:data.players["p"+data.sostav[d.from]].number+
"."+data.players["p"+data.sostav[d.from]].sname),f+=" => "+(99==d.to?"подходящий":data.players["p"+data.sostav[d.to]].number+"."+data.players["p"+data.sostav[d.to]].sname),f+=99==d.pos?" [удал.]":0<d.pos?" ["+poses[d.pos].name+"]":"",0<d.role&&(f+=" ["+roles[0<d.role?d.role:poses[d.from].def].sn+"]"),99>d.zad&&(f+=" ["+zads[d.zad].sn+(1==zads[d.zad].pm?"+":"-")+"]"),f+=nmsstda[d.stda],f+=nmsstdo[d.stdo]}$("#obzor-tc").html(g);$("#obzor-zam").html(f);for(e=1;5>=e;e++)if(h[e])for(k+="<br><br><b>Тактика"+
e+"</b>:<br>",d=1;11>=d;d++)g=data["sostav"+e][d],f=data.players["p"+data.sostav[d]].sname,k+=poses[g.pos].name+":"+f+"(",k+=roles[g.role].sn,k+=0<g.zad?","+zads[g.zad].sn+(1==zads[g.zad].pm?"+":"-"):"",k+=1==g.stda?",СтдА":"",k+=1==g.stdo?",СтдO":"",k+="), ";$("#obzor-tk").html(k);for(e=1;10>=e;e++)5>=e&&(!t&&0!=data.cap[e]&&11>=data.players["p"+data.cap[e]].sos?(h="<b>",k="</b>",t=!0):k=h="",l+=e+". "+h+(0!=data.cap[e]?data.players["p"+data.cap[e]].sname:"--")+k+"<br>",!u&&0!=data.cor[e]&&11>=data.players["p"+
data.cor[e]].sos?(h="<b>",k="</b>",u=!0):k=h="",n+=e+". "+h+(0!=data.cor[e]?data.players["p"+data.cor[e]].sname:"--")+k+"<br>",!v&&0!=data.fre[e]&&11>=data.players["p"+data.fre[e]].sos?(h="<b>",k="</b>",v=!0):k=h="",q+=e+". "+h+(0!=data.fre[e]?data.players["p"+data.fre[e]].sname:"--")+k+"<br>",!w&&0!=data.frh[e]&&11>=data.players["p"+data.frh[e]].sos?(h="<b>",k="</b>",w=!0):k=h="",m+=e+". "+h+(0!=data.frh[e]?data.players["p"+data.frh[e]].sname:"--")+k+"<br>"),!x&&0!=data.pen[e]&&11>=data.players["p"+
data.pen[e]].sos?(h="<b>",k="</b>",x=!0):k=h="",r+=e+". "+h+(0!=data.pen[e]?data.players["p"+data.pen[e]].sname:"--")+k+"<br>";$("#obzor-cap").html(l);$("#obzor-cor").html(n);$("#obzor-fre").html(q);$("#obzor-frh").html(m);$("#obzor-pen").html(r)}}});$("#tac-change,#pl-change").accordion({active:!1,collapsible:!0,heightStyle:"content",activate:function(a,c){if(void 0!=c.newPanel.attr("id")){var e=c.newPanel.attr("id").split("-");"curplchange"==e[0]&&(curplchange=parseInt(e[1],10));"curtacchange"==
e[0]&&(curtacchange=parseInt(e[1],10))}}});$("input[id^=pl-change-check],input[id^=pl-change-schet],input[id^=pl-change-stda],input[id^=pl-change-stdo]").change(function(){changePl(this.parentNode.id,this.id)});$("input[id^=pl-change-check]").button();$("[id^=pl-change-schet],[id^=pl-change-stda],[id^=pl-change-stdo]").buttonset().buttonset("disable");$("input[id^=tac-change-check],input[id^=tac-change-schet],input[id^=tac-change-tactic],input[id^=tac-change-half]").change(function(){changeTac(this.parentNode.id,
this.id)});$("input[id^=tac-change-check]").button();$("[id^=tac-change-schet], [id^=tac-change-tactic], [id^=tac-change-half]").buttonset().buttonset("disable");$("#pli-stda,#pli-stdo").buttonset();$("input[id^=pli-std]").change(function(){plInfo(this.parentNode.id,this.id)});$("select[id^=pli-]").selectmenu({width:33,change:function(a,c){var e,d;e=this.id.split("-")[1];switch(e){case "posp":e=c.item.value;0<$("#pos"+e+" .player").length&&(e=parseInt($("#pos"+e+" .player").attr("id").replace("pl",
""),10),d=data["sostav"+curtactic][sel].pos,changePlData(e,"pos",d));changePlData(sel,"pos",c.item.value);break;case "cap":case "cor":case "fre":case "frh":case "pen":case "posm":case "zad":case "role":changePlData(sel,e,c.item.value)}}});$("#pli-role,#pli-zad").selectmenu("option","width",230);$("#pli-posp,#pli-posm").selectmenu("option","width",80);$("select[id^=pl-change-]").selectmenu({width:200,disabled:!0,change:function(a,c){plChangeSelect(this.id,c.item.value,curplchange)}});$(".pl-change-pos").selectmenu("option",
"width",110);$("select[id^=tac-change-]").selectmenu({width:200,disabled:!0,change:function(a,c){var e=this.id.split("-")[2].replace(curtacchange,"");"oops"==e&&$("#theader-"+e+curtacchange+"1").text(nmsoops[c.item.value]);"del"==e&&$("#theader-"+e+curtacchange+"1").text(nmsdel[c.item.value]);data["tchange"+curtacchange][e][1]=parseInt(c.item.value,10)}});$("[id^=pl-change-slider-schet]").each(function(){var a=$(this).attr("id").split("-")[3];$(this).empty().slider({min:0,max:8,disabled:!0,slide:function(c,
e){var d=e.value-4;$("#pl-change-res-"+a+" .res2, #pheader-"+a+"1").text(d)},change:function(c,e){var d=e.value-4;$("#pl-change-res-"+a+" .res2, #pheader-"+a+"1").text(d);data["pchange"+curplchange].schet[2]=parseInt(e.value,10)}})});$("[id^=tac-change-slider-schet]").each(function(){var a=$(this).attr("id").split("-")[3];$(this).empty().slider({min:0,max:8,disabled:!0,slide:function(c,e){var d=e.value-4;$("#tac-change-res-"+a+" .res2, #theader-"+a+"1").text(d)},change:function(c,e){var d=e.value-
4;$("#tac-change-res-"+a+" .res2, #theader-"+a+"1").text(d);data["tchange"+curtacchange].schet[2]=parseInt(e.value,10)}})});$("[id^=pl-change-slider-mark],[id^=pl-change-slider-form]").each(function(){var a=$(this).attr("id").split("-")[3],c=parseInt(a.replace("mark","").replace("form",""),10),e=a.replace(c,"");$(this).empty().slider({range:"min",min:0,max:30,step:1,disabled:!0,slide:function(c,g){var f=g.value;"mark"==e&&(f=(g.value/10+5).toFixed(1));"form"==e&&(f+=70);$("#pl-change-res-"+a+" .res2, #pheader-"+
e+curplchange+"1").text(f)},change:function(c,g){var f=g.value;"mark"==e&&(f=(g.value/10+5).toFixed(1));"form"==e&&(f+=70);$("#pl-change-res-"+a+" .res2, #pheader-"+e+curplchange+"1").text(f);data["pchange"+curplchange][e][1]=parseInt(g.value,10)}})});$("[id^=tac-change-slider-time],[id^=pl-change-slider-time]").each(function(){var a=$(this).attr("id").split("-")[0],c=$(this).attr("id").split("-")[3];$(this).empty().slider({range:!0,min:0,max:120,disabled:!0,slide:function(e,d){$("#"+a+"-change-res-"+
c).find(".res1").text(d.values[0]+"мин").end().find(".res2").text(d.values[1]+"мин");$("#"+a.substring(1,0)+"header-"+c+"1").text(d.values[0]+"-"+d.values[1])},change:function(e,d){var g="pl"==a?curplchange:curtacchange,f=c.replace(g,"");$("#"+a+"-change-res-"+c).find(".res1").text(d.values[0]+"мин").end().find(".res2").text(d.values[1]+"мин");$("#"+a.substring(1,0)+"header-"+c+"1").text(d.values[0]+"-"+d.values[1]);data[a.substring(1,0)+"change"+g][f][1]=d.values[0];data[a.substring(1,0)+"change"+
g][f][2]=d.values[1]}})});$("[id^=tac-slider]").each(function(){var a=$(this).attr("id").split("-")[2];$(this).empty().slider({min:0,max:8,slide:function(c,e){$("#tac-res-"+a).text(tacNames[a][e.value])},change:function(c,e){$("#tac-res-"+a).text(tacNames[a][e.value]);data["tactic"+curtactic][a]=parseInt(e.value,10)}})});1E3<=wsize?($("#scr").remove(),sh2=50):$("#scr").slider({min:0,max:sh2,slide:function(a,c){sh1=parseInt(c.value,10);$("#plist tr:eq(0) td");$("#plist tr").each(function(){$(this).find("td:gt(4)").addClass("hid");
$(this).find("td:lt("+(5+sh1+sh2)+"):gt("+(5+sh1-1)+")").removeClass("hid")})},create:function(a,c){$("#plist tr").each(function(){$(this).find("td:gt("+(5+sh2-1)+")").addClass("hid")})}});$("#ustanovka").selectmenu({width:104,change:function(a,c){data["tactic"+curtactic].ustanovka=parseInt(c.item.value,10)}});$("#direction,#freekick,#corner,#goalkick,#offside,#kontra,#press,#pulltime,#tactics").buttonset();$("input[id^=direction],input[id^=press],input[id^=goalkick],input[id^=freekick],input[id^=corner],input[id^=offside],input[id^=kontra],input[id^=pulltime]").change(function(){changeTacticField(this.parentNode.id,
this.id)});$("#tactics > input").change(function(){setTactic(this.id.split("-")[1])});$("#pli-opeka").change(function(){setOpeka(this.value)}).on("focus",function(){setOpeka(this.value)}).keyup(function(){setOpeka(this.value)});$("#tactics2 > span").click(function(){clear(this.id.split("-")[1])});$("[id^=tac-res-]").click(function(){changeSlider("tac-slider-"+this.id.split("-")[2])});$("[id^=pl-change-res-mark], [id^=pl-change-res-form], [id^=pl-change-res-schet]").click(function(){changeSlider("pl-change-slider-"+
this.id.split("-")[3])});$("[id^=tac-change-res-schet]").click(function(){changeSlider("tac-change-slider-"+this.id.split("-")[3])});$("span[id^=plchange-res-time]").click(function(){changeSlider("pl-change-slider-"+this.id.split("-")[2],this.id.split("-")[3])});$("span[id^=tacchange-res-time]").click(function(){changeSlider("tac-change-slider-"+this.id.split("-")[2],this.id.split("-")[3])})}
function changeSlider(a,b){var c,e,d;void 0==b?(d=$("#"+a).slider("value"),$("#"+a).slider("value",d==$("#"+a).slider("option","max")?$("#"+a).slider("option","min"):d+1)):(d=$("#"+a).slider("values",b),0==b?(c=$("#"+a).slider("option","min"),e=$("#"+a).slider("values",1),c=d==c?e-1:d-1):(c=$("#"+a).slider("values",0),e=$("#"+a).slider("option","max"),c=d==e?c+1:d+1),$("#"+a).slider("values",b,c))}function setOpeka(a){data.opeka=void 0!=a&&null!=a?a:""}
function delPos(a){if(0==a)return 3;if(1==a)return 5;if(2==a)return 52;if(3==a)return 53;if(4==a)return 24}
function plChangeSelect(a,b,c){var e,d=a.split("-")[2].replace(c,"");"oops"==d||"del"==d?("oops"==d&&$("#pheader-"+d+c+"1").text(nmsoops[b]),"del"==d&&($("#pheader-"+d+c+"1").text(nmsdel[b]),99==data["pchange"+c].pos?changePlRole(delPos(b),c):changePlRole(data["pchange"+c].pos,c)),data["pchange"+c][d][1]=parseInt(b,10)):(e="","to"==d&&(e=99==b?"подходящий":data.players["p"+data.sostav[b]].number+"."+data.players["p"+data.sostav[b]].sname),"pos"==d&&(0==b?(a=$("#pl-change-from"+c).val(),12==a?changePlRole(5,
c):13==a?changePlRole(15,c):14==a?changePlRole(24,c):changePlRole(data.sostav1[a].pos,c)):(e="["+(99==b?"удал.":poses[b].name)+"]",changePlRole(99==b?delPos(data["pchange"+c].del[1]):b,c))),"role"==d&&0<b&&(e="["+roles[b].sn+"]"),"zad"==d&&(0==b&&(e="[--]"),0<b&&99!=b&&(e="["+zads[b].sn+(1==zads[b].pm?"+":"-")+"]")),"from"==d&&(12>b?(e=data.players["p"+data.sostav[b]].number+"."+data.players["p"+data.sostav[b]].sname,0==$("#pl-change-pos"+c).val()&&changePlRole(data.sostav1[b].pos,c)):(e=nms[parseInt(b,
10)-12],0==$("#pl-change-pos"+c).val()&&(12==b&&changePlRole(5,c),13==b&&changePlRole(15,c),14==b&&changePlRole(24,c)))),$("#pheader-"+d+c).text(e),data["pchange"+c][d]=parseInt(b,10),"from"==d&&(1==b?($("input#pl-change-stda"+c+"0, input#pl-change-stdo"+c+"0").prop("checked","true"),$("#pl-change-stda"+c+", #pl-change-stdo"+c).buttonset("refresh").buttonset("disable"),changePl("pl-change-stda"+c,"pl-change-stda"+c+"0"),changePl("pl-change-stdo"+c,"pl-change-stdo"+c+"0"),$("#pl-change-pos"+c+" option:eq(0)").prop("selected",
"true").parent().selectmenu("refresh"),$("#pl-change-pos"+c).selectmenu("disable"),plChangeSelect("pl-change-pos"+c,0,c)):$("#pl-change-from"+c).selectmenu("option","disabled")||($("#pl-change-pos"+c).selectmenu("enable"),$("#pl-change-stda"+c+", #pl-change-stdo"+c).buttonset("enable"))))}
function changePlRole(a,b){var c,e,d=$("select#pl-change-role"+b),g=d.val(),f=poses[a].roles,h=c=poses[a].def,k;k='<option value="0">Не менять роль</option>'+('<option value="'+c+'">'+roles[c].name+"(умолч.)</option>");for(c=0;c<f.length;c++)e=f[c],e==g&&(h=g),k+='<option value="'+e+'">'+roles[e].name+"</option>";d.html(k).find("option[value="+h+"]").prop("selected","true").end().selectmenu("refresh");plChangeSelect("pl-change-role"+b,h,curplchange)}
function getjson(a){$("#tabs").hide();curc=a;$.getJSON("jsonsostav2.php?"+clubs[curc].gurl,function(a){""!=a&&draw(a)})}
function bkjson(a,b){$("#bkresult").text("");var c,e=clubs[curc]["u"+b][a];switch(a){case "del":void 0!=data["u"+b]?$.getJSON("jsonsostav2.php?"+e,function(a){""!=a&&(0==a[0]?(delete data["u"+b],$("#dbk"+b).text(""),$("#nbk"+b+" input").val("СЛОТ "+b),$("#bkresult").html("<font color=green>УСПЕШНО</font>: Cостав успешно удален из СЛОТ "+b+".")):$("#bkresult").html("<font color=red>ОШИБКА</font>: Не получилось удалить данные из СЛОТ "+b+"."))}):$("#bkresult").html("<font color=green>УСПЕШНО</font>: данные и так отсутствуют в СЛОТ "+
b+".");break;case "get":void 0!=data["u"+b]?($("#tabs").hide(),$.getJSON("jsonsostav2.php?"+e,function(a){""!=a&&draw(a,1)})):$("#bkresult").html("<font color=red>ОШИБКА</font>: Прежде чем загрузить состав из СЛОТ "+b+", создайте запись.");break;case "name":c=String($("#nbk"+b+" input").val()).replace(/\"/g,"");void 0!=c&&""!=c&&$.ajax({url:"jsonsostav2.php?"+e,type:"POST",dataType:"json",data:"jsonData="+encodeURIComponent(c),error:function(a,c,e){$("#bkresult").html("<font color=red>ОШИБКА</font>: Не удалось изменить название у СЛОТ "+
b+".")},success:function(a){0==a[0]?($("#nbk"+b+" input").toggleClass("input-disable ui-state-active").prop("disabled","true"),$("#abk"+b).text("изменить"),curbknum=0,$("#bkresult").html("<font color=green>УСПЕШНО</font>: Успешно сохранили имя для СЛОТ "+b+".")):$("#bkresult").html("<font color=red>ОШИБКА</font>: Не удалось изменить название у СЛОТ "+b+".")}});break;case "save":if(!save){if(!checkErrors(1))return!1;save=!0;savePrepare();sData.savename=String($("#nbk"+b+" input").val()).replace(/\"/g,
"");$.ajax({url:"jsonsostav2.php?"+e,type:"POST",dataType:"json",data:"jsonData="+JSON.stringify(sData),beforeSend:function(a){$("#bkresult").html("Сохраняем состав в СЛОТ "+b+"...")},complete:function(a,b){save=!1},error:function(a,c,e){$("#bkresult").html("<font color=red>ОШИБКА</font>: Не удалось сохранить состав в СЛОТ "+b+".")},success:function(a){0==a[0]?($("#dbk"+b).text(a[1]),void 0==data["u"+b]?data["u"+b]={num:b,dt:a[1],name:"СЛОТ "+b}:data["u"+b].dt=a[2],$("#bkresult").html("<font color=green>УСПЕШНО</font>: Текущий состав успешно сохранён в СЛОТ "+
b+", не забудьте сохранить состав на следующую игру!")):$("#bkresult").html("<font color=red>ОШИБКА</font>: Не получилось сохранить состав в СЛОТ "+b+".<br>"+a[1])}})}}}
function postjson(){if(!save){if(!checkErrors())return!1;save=!0;savePrepare();$.ajax({url:"jsonsostav2.php?"+clubs[curc].uurl,type:"POST",dataType:"json",data:"jsonData="+JSON.stringify(sData),beforeSend:function(a){$("#sres").html("Сохраняем...")},complete:function(a,b){save=!1},error:function(a,b,c){$("#sres").html("<font color=red>ОШИБКА!</font> данные не были сохранены!")},success:function(a){$("#sres").html((0==a[0]||10==a[0]?"<font color=green>СОХРАНЕНО</font>: ":"<font color=red>ОШИБКА СОХРАНЕНИЯ СОСТАВА</font>:<br>")+
a[1])}})}return!1}function editName(a){void 0!=data["u"+a]?0==curbknum?(curbknum=a,$("#nbk"+a+" input").toggleClass("input-disable ui-state-active").prop("disabled","").select().focus(),$("#abk"+a).text("сохранить")):a!=curbknum?$("#bkresult").html("<font color=red>ОШИБКА</font>: Вначале необходимо закончить переименование СЛОТ "+curbknum+"."):bkjson("name",a):$("#bkresult").html("<font color=red>ОШИБКА</font>: Прежде чем менять имя для СЛОТ "+a+", создайте запись.")}
function checkRecievedData(){var a,b,c,e,d=18,g=0;e=["cap","cor","fre","frh","pen"];var f=6E4<clubs[curc].id?!0:!1,h=[];void 0!=data.weather&&$("#pole-all").toggleClass("sun "+data.weather);void 0!=data.imgPl&&void 0!=data.imgPl.url&&(imgPl=data.imgPl.url);void 0!=data.frc&&""!=data.frc&&(numbercolor=data.frc);for(a in e)for(b in c=e[a],data[c])data[c].hasOwnProperty(b)&&0<b&&void 0==data.players["p"+data[c][b]]&&(data[c][b]=0);for(a=1;a<data.sostav.length;a++)b=data.players["p"+data.sostav[a]],void 0==
b||0<b.inj||0<b.sus?(h.push(a),data.sostav[a]=0):b.sos=a;e=1;for(a in data.players)if(data.players.hasOwnProperty(a)){b=data.players[a];1==b.fake&&(g++,b.fname="",b.sname="Дублёр"+g,b.form=70,b.morale=90,b.syg=0,b.age=15,b.inj=0,b.sus=0,b.position="");b.syg=parseInt(b.syg/20*100,10);f&&(b.number=e,e++);if(void 0==b.number||0==b.number)b.number="--";0<b.games&&(b.rating=(b.rating/b.games).toFixed(1));if(void 0==b.sos||0==b.sos)0<h.length&&0==b.inj&&0==b.sus?(c=h.shift(),data.sostav[c]=b.id,b.sos=c):
(d++,data.sostav[d]=b.id,b.sos=d)}$("#pli-opeka").attr("value",data.opeka)}
function draw(a,b){var c,e,d;data=a;checkRecievedData();$("div#pl-change, div#tac-change").accordion("option","active",!1);$("div#tabs").tabs("option","active",0);$("tbody#osnova tr:gt(0), tbody#zamena tr").html("");$("tbody#other tr:gt(0)").remove();$(".tactic-active").removeClass("tactic-active");$("input#tactic-1").prop("checked","true").parent().buttonset("refresh");curtactic=0;setTactic(1);for(c=12;c<data.sostav.length;c++)updatePlayerList(c);clearSetChange();for(c=1;c<=zamnum;c++)curplchange=
c,setPlChange(),curtacchange=c,setTacChange();1!=b&&$("#sres").html("Последнее сохранение: "+data.lastsave);for(c=1;5>=c;c++)e="",d="СЛОТ "+c,void 0!=data["u"+c]&&(e=data["u"+c].dt,d=data["u"+c].name),$("#dbk"+c).text(e),$("#nbk"+c+" input").val(d);$("div#tabs").show()}
function setRoleZad(a){var b=data["sostav"+curtactic][a],c=poses[b.pos];0!=b.role&&-1!=$.inArray(b.role,c.roles)||changePlData(a,"role",c.def,curtactic);-1==$.inArray(b.zad,c.zads)&&changePlData(a,"zad",0,curtactic);sel==a&&drawRoleZad(a)}
function drawRoleZad(a){var b,c,e,d,g,f,h=data["sostav"+curtactic],k=h[a],l=poses[k.pos],n=b=l.def,q=0,m='<option value="'+b+'">'+roles[b].name+" (умолч.)</option>";optionszad='<option value="0">---</option>';for(b=0;b<l.roles.length;b++){e=l.roles[b];d=roles[e];g="";f=0;if(void 0!=d.num){for(c=1;c<h.length;c++)c!=a&&h[c].role==e&&f++;f>=d.num&&(g=" disabled")}m+='<option value="'+e+'"'+g+">"+d.name+"</option>";e==k.role&&(n=e)}for(b=0;b<l.zads.length;b++)a=l.zads[b],optionszad+='<option value="'+
a+'">'+zads[a].name+"</option>",a==k.zad&&(q=a);$("select#pli-role option, select#pli-zad option").remove();$("select#pli-role").append(m);$('select#pli-role option[value="'+n+'"]').prop("selected","true");$("select#pli-zad").append(optionszad);$('select#pli-zad option[value="'+q+'"]').prop("selected","true");$("select#pli-role, select#pli-zad").selectmenu("refresh")}
function changePlData(a,b,c,e){void 0==e&&(e=curtactic);c=parseInt(c,10);var d,g;d=data.sostav[a];var f=data["sostav"+e][a];g=data[b];switch(b){case "pos":$("input#pli-stda, input#pli-stdo").buttonset(1==c?"disable":"enable");$("select#pli-posm, select#pli-posp").selectmenu(1==c?"disable":"enable");if(1==e)for(d=1;d<=zamnum;d++)g=data["pchange"+d],g.from==a&&0==g.pos&&changePlRole(c,d);f[b]=c;setRoleZad(a);drawPlayerCard(a);updatePlayerList11(a,b,c);countSyg(e);break;case "posm":f[b]=f.pos!=c?c:0;
drawPlayerCard(a);break;case "role":f[b]=c;10==c?$("input#pli-opeka").prop("disabled","").removeClass("ui-state-disabled").addClass("ui-state-default"):$("input#pli-opeka").prop("disabled","true").removeClass("ui-state-default").addClass("ui-state-disabled");drawPlayerCard11(a,b,c);break;case "zad":f[b]=c;drawPlayerCard11(a,b,c);break;case "stda":case "stdo":f[b]=c;updatePlayerList11(a,b,c);sel==a&&$("#pli-"+b+c).prop("checked","true").parent().buttonset("refresh");break;case "cap":case "cor":case "fre":case "frh":case "pen":a=
$.inArray(d,g),-1==a&&(a=0),0!=c?0==a?0==g[c]?g[c]=d:g.splice(c,0,d):(g.splice(a,1),g.splice(c,0,d)):g[a]=0,g.length="pen"==b?11:6}}
function savePrepare(){var a,b,c,e,d,g={"01":0,10:1,11:2,"00":2},f={101:0,"010":1,111:2,110:3,"011":4,100:5,"001":6,"000":2},h=[];sData={};for(a=1;11>=a;a++)h.push({pos:parseInt(data.sostav1[a].pos,10),num:parseInt(a,10)});h.sort(function(a,b){return a.pos<b.pos?-1:a.pos>b.pos?1:0});for(a=0;11>a;a++)for(c=h[a].num,e=a+1,sData["pid_"+e]=parseInt(data.sostav[c],10),b=1;5>=b;b++)d=data["sostav"+b][c],sData["p"+b+"_"+e]=d.pos,sData["pm"+b+"_"+e]=d.posm,sData["z"+b+"_"+e]=d.zad+20*d.stda+40*d.stdo,sData["r"+
b+"_"+e]=d.role;for(a=12;18>=a;a++)sData["pid_"+a]=parseInt(data.sostav[a],10);for(a=1;10>=a;a++)sData["pen"+a]=parseInt(data.pen[a],10);for(a=1;5>=a;a++)sData["cap"+a]=parseInt(data.cap[a],10),sData["cor"+a]=parseInt(data.cor[a],10),sData["fre"+a]=parseInt(data.fre[a],10),sData["frh"+a]=parseInt(data.frh[a],10),d=data["tactic"+a],sData["tactic"+a]=String(d.ustanovka)+d.pass+f[d.direction.join("")]+d.aggress+f[d.freekick.join("")]+g[d.corner.join("")]+d.press+d.offside+d.ward+d.pulltime+d.impro+d.temp+
f[d.goalkick.join("")]+d.defline+d.defwidth+d.attwidth+d.kontra;for(a=1;a<=zamnum;a++){d=data["pchange"+a];c=d.from;for(b=0;11>b;b++)if(h[b].num==c){c=b+1;break}sData["s"+a]=String(d.time[0])+("00"+d.time[1]).slice(-3)+("00"+d.time[2]).slice(-3)+d.form[0]+("0"+d.form[1]).slice(-2)+d.mark[0]+("0"+d.mark[1]).slice(-2)+d.schet.join("")+d.del.join("")+d.oops.join("")+("0"+d.pos).slice(-2)+("0"+d.role).slice(-2)+("0"+d.zad).slice(-2)+d.stda+d.stdo+("0"+c).slice(-2)+("0"+d.to).slice(-2);d=data["tchange"+
a];sData["t"+a]=d.time[0]+("00"+d.time[1]).slice(-3)+("00"+d.time[2]).slice(-3)+d.schet.join("")+d.del.join("")+d.oops.join("")+d.tactic+d.half}sData.opeka=encodeURIComponent(String(data.opeka).replace(/\"/g,"").replace(/\t/g,""))}
function setTacticFields(){var a,b,c,e,d,g=data["tactic"+curtactic];$("select#ustanovka option[value="+g.ustanovka+"]").prop("selected","true").parent().selectmenu("refresh");b="pass impro temp aggress ward defline defwidth attwidth".split(" ");for(c in b)a=b[c],$("#tac-slider-"+a).slider("value",g[a]);b=["direction","goalkick","freekick","corner"];for(c in b){a=b[c];d=g[a];for(e in d)d.hasOwnProperty(e)&&$("#"+a+e).prop("checked",1==d[e]?"true":"");$("#"+a).buttonset("refresh")}b=["press","offside",
"kontra","pulltime"];for(c in b)a=b[c],$("#"+a+g[a]).prop("checked","true").parent().buttonset("refresh")}function changeTacticField(a,b){var c=$("#"+b).prop("checked");b=parseInt(b.replace(a,""),10);$("#"+a+b).blur();-1<"direction freekick goalkick corner".indexOf(a)?data["tactic"+curtactic][a][b]=c?1:0:data["tactic"+curtactic][a]=b}
function checkErrors(a){var b;for(a=1;a<=zamnum;a++)if(b=data["tchange"+a],0<b.del[0]+b.oops[0]+b.schet[0]+b.time[0]&&0==b.tactic)return $("#sres").html("<font color=red>ОШИБКА!</font> данные не были сохранены!<br> в сменах тактики для "+a+" стоит переход на тактику 0!"),!1;return!0}
function setTactic(a){if(a==curtactic||settc)return!1;settc=!0;curtactic=a;var b;for(b=1;11>=b;b++)setRoleZad(b),drawPlayerCard(b),0==$("tr#plsos"+b+" td").length?updatePlayerList(b):(updatePlayerList11(b,"pos",data["sostav"+a][b].pos),updatePlayerList11(b,"stda",data["sostav"+a][b].stda),updatePlayerList11(b,"stdo",data["sostav"+a][b].stdo));setTacticFields();countSyg(a);settc=!1}
function setPlNameToSubs(a,b,c,e){var d;for(p=1;p<=zamnum;p++)$("#pl-change-"+(11>=a?"from":"to")+p+" option[value="+a+"]").text(e+" "+b+(11<a?void 0!=c?" ("+c+")":"":"")).parent().selectmenu("refresh"),d=$("#pl-change-from"+p+" option:selected").val(),11>=a&&d==a&&$("#pheader-from"+p).text(a+"."+b),d=$("#pl-change-to"+p+" option:selected").val(),d==a&&$("#pheader-to"+p).text(a+"."+b)}
function checkPos(a,b){if(1==a&&-1<b.indexOf("GK"))return!0;var c=!1,e=!1;if(-1<b.indexOf("L")&&(3==a||8==a||13==a||18==a)||-1<b.indexOf("R")&&(7==a||12==a||17==a||22==a)||-1<b.indexOf("C")&&(2==a||4==a||5==a||6==a||9==a||10==a||11==a||14==a||15==a||16==a||19==a||20==a||21==a||23<=a))c=!0;c&&(-1<b.indexOf("SW")&&2==a||-1<b.indexOf("DF")&&3<=a&&7>=a||-1<b.indexOf("DM")&&8<=a&&17>=a||-1<b.indexOf("AM")&&13<=a&&22>=a||-1<b.indexOf("MF")&&13<=a&&17>=a||-1<b.indexOf("FW")&&(23<=a&&25>=a||18==a||22==a))&&
(e=!0);return c&&e?!0:!1}function updatePlayerList11(a,b,c){var e="";switch(b){case "pos":11>=a&&(checkPos(c,data.players["p"+data.sostav[a]].position)?$("#position"+a).removeClass("wrong"):$("#position"+a).addClass("wrong"));case "posp":b="posp";e=poses[c].name;break;case "stda":case "stdo":0<c&&(e=simb[b])}$("td#"+b+a).html(e).attr("title","")}
function updatePlayerList(a){var b,c,e,d,g,f=data.players["p"+data.sostav[a]];e=' class="back8"';var h="form morale syg propustil passing vision crossing technique marking freekicks corners finishing longshots dribbling tackling heading positioning strength pace workrate stamina leadership reflexes handling age games goals passes rating mom".split(" ");if(void 0==f||0==a)return!1;11>=a?c=data["sostav"+curtactic][a]:e=' class="tdclss back2"';e='<td id="posp'+a+'" '+e+'></td><td id="stda'+a+'" '+e+
'></td><td id="stdo'+a+'" '+e+'></td><td id="sname'+a+'" class="rt '+(0<f.inj?"wrong":"")+(0<f.sus?"marksus":"")+'" title="'+(""!=f.fname&&void 0!=f.fname?f.fname+" ":"")+f.sname+'">'+f.number+" "+(""!=f.fname&&void 0!=f.fname?f.fname[0]+".":"")+f.sname+'</td><td id="position'+a+'" class="rt '+(11>=a&&!checkPos(c.pos,f.position)?"wrong":"")+'" title="'+f.position+'">'+f.position+"</td>";for(b in h)g=h[b],d=(4>b||b>=h.length-6?"back8":g)+(-1<cursk.indexOf("#"+g+"#")?" marked":"")+(7==b||10==b||13==
b||17==b||20==b?" rt":"")+(b>=sh2+sh1||b<sh1?" hid":""),e+='<td id="'+g+a+'" class="'+d+'">'+(void 0==f[g]?"":f[g])+"</td>";11>=a?(setPlNameToSubs(a,(""!=f.fname&&void 0!=f.fname?f.fname[0]+".":"")+f.sname,f.position,f.number),$("#plsos"+a).html(e),updatePlayerList11(a,"stda",c.stda),updatePlayerList11(a,"stdo",c.stdo),updatePlayerList11(a,"posp",c.pos),1==c.pos&&$("#stda"+a+", #stdo"+a).removeClass("back8").addClass("tdclss").addClass("back2")):18>=a?(setPlNameToSubs(a,(""!=f.fname&&void 0!=f.fname?
f.fname[0]+".":"")+f.sname,f.position,f.number),$("#plsos"+a).html(e)):1==$("#plsos"+a).length?$("#plsos"+a).html(e):$("#other").append('<tr id="plsos'+a+'">'+e+"</tr>");$("#plsos"+a).find("td:not(.tdclss)").bind("click",function(){selectPlayer(a,0,this.id)});1==f.school?$("#plsos"+a).addClass("school"):$("#plsos"+a).removeClass("school");plFilterPlayer(curfl,f)?18<a?$("#plsos"+a).show():$("#plsos"+a).removeClass("filtered"):18<a?$("#plsos"+a).hide():$("#plsos"+a).addClass("filtered")}
function drawPlayerCard11(a,b,c){var e="--",d="",g="";switch(b){case "role":c=roles[c];$("div#pl"+a+" span.player-"+b).html(c.sn).attr("title",c.name).attr("style",g);break;case "zad":0<c&&(c=zads[c],e=c.sn,d=c.name,g=0<c.pm?"background:#1BDC25;":"background:#EEDD82;"),$("div#pl"+a+" span.player-"+b).html(e).attr("title",d).attr("style",g)}}
function drawPlayerCard(a){var b,c=data["sostav"+curtactic][a];b=data.players["p"+data.sostav[a]];var e=1==c.pos?" GK":"",d=zads[c.zad];$("#pl"+a).remove();b='<div class="player" id="pl'+a+'" onClick="selectPlayer('+a+', 1);"><span class="player-form" style="width:'+parseInt(b.form/5,10)+"px;background:"+(89<b.form?"#09DD09":80>b.form?"red":"yellow")+';"></span><span class="player-morale" style="width:'+parseInt(b.morale/5,10)+"px;background:"+(89<b.morale?"#09DD09":80>b.morale?"red":"yellow")+';"></span><img class="player-img'+
e+'" src="'+(1==c.pos?imgGK:imgPl)+'"><span class="player-number'+e+'" style="color:'+numbercolor+';">&nbsp;</span><div class="player-info'+e+'"><span class="player-role" title="'+roles[c.role].name+'">'+roles[c.role].sn+'</span><span class="player-zad" title="'+d.name+'"'+(0<c.zad?' style="'+(0<d.pm?"background:#1BDC25;":"background:#EEDD82;")+'"':"")+">"+d.sn+'</span><span class="player-name'+e+(void 0==b.position||checkPos(c.pos,b.position)?"":" wrong")+'" title="'+(""!=b.fname?b.fname+" ":"")+
b.sname+'">'+(1!=a&&7<b.sname.length?b.sname.substring(6,0)+"..":(6>b.sname.length?""!=b.fname?b.fname.substring(1,0)+".":"":"")+b.sname)+"</span></div></div>";$("#pos"+c.pos).html(b);drawArrow(a,c.posm);sel==a&&(drawSelect(a),$("#pl"+a).addClass("player-sel").find(".player-name").addClass("player-name-sel"))}function selectPole(a){""!=sel&&1<sel&&11>=sel&&(arrOn?changePlData(sel,"posm",a,curtactic):0==$("#pos"+a+" .player").length&&changePlData(sel,"pos",a,curtactic))}
function drawSelect(a){var b,c,e,d,g;d=data.players["p"+data.sostav[a]];$("div#plname").text(d.fname+" "+d.sname);$("div#plage").html((""!=d.position?"<b>"+d.position+"</b>, ":"")+"Возраст: "+d.age);$("div#plinfo").text("Сыгранность: "+d.syg+"%");$("div#plform").text("Форма: "+d.form+"%, Мораль: "+d.morale+"%");$("img#pli-img").attr("src",void 0!=d.position&&-1<d.position.indexOf("GK")?imgGK:imgPl);e="passing vision crossing technique marking freekicks corners finishing longshots dribbling tackling heading positioning strength pace workrate stamina leadership reflexes handling".split(" ");
for(c in e)b=d[e[c]],void 0==b&&(b=1),$("#pli-skills #"+e[c]+"_").html(b);-1<d.position.indexOf("GK")?($("#pli-skills td[id^=marking]").hide(),$("#pli-skills td[id^=reflexes]").show(),$("#pli-skills td[id^=corners]").hide(),$("#pli-skills td[id^=handling]").show(),$("#pli-skills td#heading").text("Игра на вых.")):($("#pli-skills td[id^=reflexes]").hide(),$("#pli-skills td[id^=marking]").show(),$("#pli-skills td[id^=handling]").hide(),$("#pli-skills td[id^=corners]").show(),$("#pli-skills td#heading").text("Игра головой"));
e=["cap","cor","fre","frh","pen"];for(c in e)b=e[c],g=$.inArray(parseInt(d.id,10),data[b]),-1==g&&(g=0),$("select#pli-"+b).find("option[value="+g+"]").prop("selected","true").end().selectmenu("refresh");11>=a?(d=data["sostav"+curtactic][a],drawRoleZad(a),$("select#pli-posp option[value="+(1==d.pos?0:d.pos)+"], select#pli-posm option[value="+d.posm+"]").prop("selected","true").parent().selectmenu("refresh").selectmenu(1==d.pos?"disable":"enable"),$("select#pli-role option[value="+d.role+"], select#pli-zad option[value="+
d.zad+"]").prop("selected","true").parent().selectmenu("refresh"),10==parseInt(d.role,10)?$("input#pli-opeka").prop("disabled","").removeClass("ui-state-disabled").addClass("ui-state-default"):$("input#pli-opeka").prop("disabled","true").removeClass("ui-state-default").addClass("ui-state-disabled"),$("input#pli-stda"+d.stda+", input#pli-stdo"+d.stdo).prop("checked","true").parent().buttonset("refresh").buttonset(1==d.pos?"disable":"enable"),$("div#pl-on-pole").show()):$("div#pl-on-pole").hide()}
function drawSelectSwitch(a){$("#plsos"+a).toggleClass("selpl");$("#pl"+a).toggleClass("player-sel").find(".player-name").toggleClass("player-name-sel");1E3>wsize&&$("#settingstac").toggle();$("#settingspl").toggle()}
function selectPlayer(a,b,c){var e;if(void 0!=c&&-1<c.indexOf("std"))return b=c.replace(a,""),changePlData(a,b,1==data["sostav"+curtactic][a][b]?0:1,curtactic),!1;if(sel==a)sel="",drawSelectSwitch(a);else if(""==sel)sel=a,drawSelect(a),drawSelectSwitch(a);else if(!arrOn)c=data.players["p"+data.sostav[a]],e=data.players["p"+data.sostav[sel]],1==b||0<c.inj||0<c.sus||0<e.inj||0<e.sus?(drawSelectSwitch(sel),sel=a,drawSelect(a),drawSelectSwitch(a)):replacePlayers(sel,a);else if(11<a||0==b)drawSelectSwitch(sel),
sel=a,drawSelect(a),drawSelectSwitch(a)}function replacePlayers(a,b){var c=data.sostav[a],e=data.sostav[b];data.sostav[a]=e;data.sostav[b]=c;data.players["p"+c].sos=b;data.players["p"+e].sos=a;selectPlayer(sel);11>=a&&drawPlayerCard(a);11>=b&&drawPlayerCard(b);updatePlayerList(a);updatePlayerList(b);countSyg()}function SwitchArrows(){$("#swr").toggleClass("swrOn");arrOn=arrOn?!1:!0}
function drawArrow(a,b,c){var e,d,g,f,h;h=window.eval&&eval("/*@cc_on 1;@*/")&&(/msie (\d+)/i.exec(navigator.userAgent)||[,!0])[1];freeArrow(a);if(void 0!=h&&9>h||0==b)return!1;e=data["sostav"+curtactic][a].pos;d=poses[b].x-poses[e].x;g=poses[e].y-poses[b].y;(0!=d||0!=g)&&1<b&&(0!=c&&$("#posm"+plid).text("->"),void 0==c&&(c=-70),0==c&&0<$("div#pos"+e+" .player-placeholder").length&&(c=-20),0!=g&&(c-=20),b=Math.sqrt(d*d+g*g),f=Math.round(Math.sqrt(d*xpx*d*xpx+g*ypx*g*ypx)/b),d=Math.atan2(d*xpx,g*ypx),
g="height:"+f+"px;",g=9==h?g+("-ms-transform-origin: center bottom;-ms-transform: translate(0,"+c+"px) rotate("+d+"rad)"+(0==b?"":" scaleY("+b+");")):g+("-webkit-transform-origin: center bottom;-webkit-transform: translate(0,"+c+"px) rotate("+d+"rad)"+(0==b?"":" scaleY("+b+")")+";transform-origin: center bottom;transform: translate(0,"+c+"px) rotate("+d+"rad)"+(0==b?"":" scaleY("+b+")")+";"),$("div#pos"+e).append('<img class="arr" id="arr'+a+'" src="system/img/sostav/arrow.png" style="'+g+'">'))}
function showTeams(a){$("#cname").html("");for(var b in clubs)$("#cname").append(clubs[b].name+(1==b?" (ИО)":"")+': <a onclick="getjson('+b+')" style="cursor:pointer;">состав на матч</a><br>');void 0!=a&&getjson(a)}function freeArrow(a){$("img#arr"+a).remove()}
function setTacChange(){var a=data["tchange"+curtacchange];1==a.time[0]&&($("#tac-change-check-time"+curtacchange+"0").prop("checked","true").button("refresh"),changeTac("tac-change-check-time"+curtacchange,"tac-change-check-time"+curtacchange+"0"));$("#tac-change-slider-time"+curtacchange).slider("values",[a.time[1],a.time[2]]);1==a.schet[0]&&($("#tac-change-check-schet"+curtacchange+"0").prop("checked","true").button("refresh"),changeTac("tac-change-check-schet"+curtacchange,"tac-change-check-schet"+
curtacchange+"0"));$("#tac-change-slider-schet"+curtacchange).slider("value",a.schet[2]);$("#tac-change-schet"+curtacchange+a.schet[1]).prop("checked","true").parent().buttonset("refresh");changeTac("tac-change-schet"+curtacchange,"tac-change-schet"+curtacchange+a.schet[1]);1==a.del[0]&&($("#tac-change-check-del"+curtacchange+"0").prop("checked","true").button("refresh"),changeTac("tac-change-check-del"+curtacchange,"tac-change-check-del"+curtacchange+"0"));$("select#tac-change-del"+curtacchange).find("option[value="+
a.del[1]+"]").prop("selected","true").end().selectmenu("refresh");$("#theader-del"+curtacchange+"1").text(nmsdel[a.del[1]]);1==a.oops[0]&&($("#tac-change-check-oops"+curtacchange+"0").prop("checked","true").button("refresh"),changeTac("tac-change-check-oops"+curtacchange,"tac-change-check-oops"+curtacchange+"0"));$("select#tac-change-oops"+curtacchange).find("option[value="+a.oops[1]+"]").prop("selected","true").end().selectmenu("refresh");$("#theader-oops"+curtacchange+"1").text(nmsoops[a.oops[1]]);
$("#tac-change-tactic"+curtacchange+a.tactic).prop("checked","true").parent().buttonset("refresh");0<a.tactic&&$("#theader-tactic"+curtacchange).text("Тактика "+a.tactic);$("#tac-change-half"+curtacchange+a.half).prop("checked","true").parent().buttonset("refresh");0<a.half&&$("#theader-half"+curtacchange).text("[только установку]")}
function clearSetChange(){chead={};$("input[id^=pl-change-check],input[id^=tac-change-check]").prop("checked","").button("refresh");$("input[id^=pl-change-schet], input[id^=pl-change-stda], input[id^=pl-change-stdo], input[id^=tac-change-schet], input[id^=tac-change-tactic], input[id^=tac-change-half]").buttonset("disable");$("select[id^=pl-change-], select[id^=tac-change-]").selectmenu("disable");$("[id^=pl-change-slider], [id^=tac-change-slider]").slider("disable");$("[id^=pl-change-res]").addClass("pl-change-res-disabled").removeClass("pl-change-res-active");
$("[id^=tac-change-res]").addClass("tac-change-res-disabled").removeClass("tac-change-res-active");$("input[id^=tac-change-tactic] + label").removeClass("ui-state-active");$("span[id^=theader-] > span[id^=theader-]").html("");$("h3 > span[id^=pheader-], h3 > span[id^=theader-]").hide();$("span[id*=header]:not(span[id*=-])").show()}
function setPlChange(){var a=data["pchange"+curplchange],b=a.role;1==a.time[0]&&($("#pl-change-check-time"+curplchange+"0").prop("checked","true").button("refresh"),changePl("pl-change-check-time"+curplchange,"pl-change-check-time"+curplchange+"0"));$("#pl-change-slider-time"+curplchange).slider("values",[a.time[1],a.time[2]]);1==a.form[0]&&($("#pl-change-check-form"+curplchange+"0").prop("checked","true").button("refresh"),changePl("pl-change-check-form"+curplchange,"pl-change-check-form"+curplchange+
"0"));$("#pl-change-slider-form"+curplchange).slider("value",a.form[1]);1==a.mark[0]&&($("#pl-change-check-mark"+curplchange+"0").prop("checked","true").button("refresh"),changePl("pl-change-check-mark"+curplchange,"pl-change-check-mark"+curplchange+"0"));$("#pl-change-slider-mark"+curplchange).slider("value",a.mark[1]);1==a.schet[0]&&($("#pl-change-check-schet"+curplchange+"0").prop("checked","true").button("refresh"),changePl("pl-change-check-schet"+curplchange,"pl-change-check-schet"+curplchange+
"0"));$("#pl-change-slider-schet"+curplchange).slider("value",a.schet[2]);$("#pl-change-schet"+curplchange+a.schet[1]).prop("checked","true").parent().buttonset("refresh");changePl("pl-change-schet"+curplchange,"pl-change-schet"+curplchange+a.schet[1]);1==a.del[0]&&($("#pl-change-check-del"+curplchange+"0").prop("checked","true").button("refresh"),changePl("pl-change-check-del"+curplchange,"pl-change-check-del"+curplchange+"0"));$("select#pl-change-del"+curplchange).find("option[value="+a.del[1]+
"]").prop("selected","true").end().selectmenu("refresh");$("#pheader-del"+curplchange+"1").text(nmsdel[a.del[1]]);1==a.oops[0]&&($("#pl-change-check-oops"+curplchange+"0").prop("checked","true").button("refresh"),changePl("pl-change-check-oops"+curplchange,"pl-change-check-oops"+curplchange+"0"));$("select#pl-change-oops"+curplchange).find("option[value="+a.oops[1]+"]").prop("selected","true").end().selectmenu("refresh");$("#pheader-oops"+curplchange+"1").text(nmsoops[a.oops[1]]);$("select#pl-change-from"+
curplchange).find("option[value="+a.from+"]").prop("selected","true").end().selectmenu("refresh");plChangeSelect("pl-change-from"+curplchange,a.from,curplchange);$("select#pl-change-to"+curplchange).find("option[value="+a.to+"]").prop("selected","true").end().selectmenu("refresh");$("#pheader-to"+curplchange).text(99==a.to?"подходящий":data.players["p"+data.sostav[a.to]].number+"."+data.players["p"+data.sostav[a.to]].sname);$("select#pl-change-pos"+curplchange).find("option[value="+a.pos+"]").prop("selected",
"true").end().selectmenu("refresh");plChangeSelect("pl-change-pos"+curplchange,a.pos,curplchange);$("select#pl-change-role"+curplchange).find("option[value="+b+"]").prop("selected","true").end().selectmenu("refresh");$("#pheader-role"+curplchange).text(0<b?"["+roles[b].sn+"]":"");plChangeSelect("pl-change-role"+curplchange,b,curplchange);$("select#pl-change-zad"+curplchange).find("option[value="+a.zad+"]").prop("selected","true").end().selectmenu("refresh");$("#pheader-zad"+curplchange).text(99>a.zad?
"["+zads[a.zad].sn+(1==zads[a.zad].pm?"+":"-")+"]":"");$("#pl-change-stda"+curplchange+a.stda).prop("checked","true").parent().buttonset("refresh");$("#pheader-stda"+curplchange).text(nmsstda[a.stda]);$("#pl-change-stdo"+curplchange+a.stdo).prop("checked","true").parent().buttonset("refresh");$("#pheader-stdo"+curplchange).text(nmsstdo[a.stdo])}
function changePl(a,b,c){var e;e=$("#"+b).prop("checked");var d=a.split("-")[3];$("#"+b).blur();void 0==c&&(c=curplchange);b=parseInt(b.replace(a,""),10);a=="pl-change-check-"+d?(b=d.replace(c,""),data["pchange"+c][b][0]=e?1:0,$("#pl-change-res-"+d).toggleClass("pl-change-res-disabled pl-change-res-active"),$("#pl-change-slider-"+d).slider(e?"enable":"disable"),d=="schet"+c&&$("[id^=pl-change-"+d+"]").buttonset(e?"enable":"disable"),d=="oops"+c&&$("#pl-change-"+d).selectmenu(e?"enable":"disable"),
d=="del"+c&&$("#pl-change-"+d).selectmenu(e?"enable":"disable"),changeHeader("p",c,d,e)):a=="pl-change-schet"+c?(e=0==b?"min":2==b?"max":"",$("#pl-change-slider-schet"+c).slider("option","range",e),$("#pl-change-res-schet"+c+" .res1").text(schetNames[b]),$("#pheader-schet"+c+"0").text(schetNamesShort[b]),data["pchange"+c].schet[1]=parseInt(b,10)):a=="pl-change-stda"+c?($("#pheader-stda"+c).text(nmsstda[b]),data["pchange"+c].stda=parseInt(b,10)):a=="pl-change-stdo"+c&&($("#pheader-stdo"+c).text(nmsstdo[b]),
data["pchange"+c].stdo=parseInt(b,10))}
function changeHeader(a,b,c,e){void 0==chead[a+b]&&(chead[a+b]=0);e?(chead[a+b]++,$("#"+a+"header"+b).hide(),$("#"+a+"header-"+c+",#"+a+"header-action"+b).show()):(chead[a+b]--,$("#"+a+"header-"+c).hide(),0==chead[a+b]&&($("#"+a+"header"+b).show(),$("#"+a+"header-action"+b).hide()));c=0<chead[a+b]?"enable":"disable";if("p"==a){if($("#pl-change-from"+b+", #pl-change-to"+b+", #pl-change-role"+b+", #pl-change-zad"+b).selectmenu(c),"disable"==c||"enable"==c&&1<data["pchange"+b].from)$("#pl-change-pos"+
b).selectmenu(c),$("#pl-change-stda"+b+", #pl-change-stdo"+b).buttonset(c)}else $("#tac-change-tactic"+b+", #tac-change-half"+b).buttonset(c)}
function changeTac(a,b,c){var e;e=$("#"+b).prop("checked");var d=a.split("-")[3];$("#"+b).blur();void 0==c&&(c=curtacchange);b=parseInt(b.replace(a,""),10);a=="tac-change-check-"+d?(b=d.replace(c,""),data["tchange"+c][b][0]=e?1:0,$("#tac-change-res-"+d).toggleClass("tac-change-res-disabled tac-change-res-active"),$("#tac-change-slider-"+d).slider(e?"enable":"disable"),d=="schet"+c&&$("[id^=tac-change-"+d+"]").buttonset(e?"enable":"disable"),d=="oops"+c&&$("#tac-change-"+d).selectmenu(e?"enable":"disable"),
d=="del"+c&&$("#tac-change-"+d).selectmenu(e?"enable":"disable"),changeHeader("t",c,d,e)):a=="tac-change-schet"+c?(e=0==b?"min":2==b?"max":"",$("#tac-change-slider-schet"+c).slider("option","range",e),$("#tac-change-res-schet"+c+" .res1").text(schetNames[b]),$("#theader-schet"+c+"0").text(schetNamesShort[b]),data["tchange"+c].schet[1]=parseInt(b,10)):a=="tac-change-tactic"+c?($("#theader-tactic"+c).text("Тактика "+b),data["tchange"+c].tactic=parseInt(b,10)):a=="tac-change-half"+c&&($("#theader-half"+
c).text(1==b?"[только установку]":""),data["tchange"+c].half=parseInt(b,10))}function countSyg(a){void 0==a&&(a=curtactic);var b,c;tpl=[];tdf=[];for(b=1;11>=b;b++)c=data["sostav"+a][b],tpl.push("p"+data.sostav[b]),2<=c.pos&&7>=c.pos&&tdf.push("p"+data.sostav[b]);sygdf=sygpl=0;for(b in tpl)sygpl+=data.players[tpl[b]].syg;for(b in tdf)sygdf+=data.players[tdf[b]].syg;sygpl/=11;sygdf/=tdf.length;$("#sygpl").text(100==sygpl?sygpl:sygpl.toFixed(1));$("#sygdf").text(100==sygdf?sygdf:sygdf.toFixed(1))}
function clear(a){var b,c,e,d;if("p"==a)for(b=1;b<=zamnum;b++)for(c in a="time mark form schet del oops".split(" "),a)e=a[c],1==data["pchange"+b][e][0]&&($("#pl-change-check-"+e+b+"0").prop("checked","").button("refresh"),changePl("pl-change-check-"+e+b,"pl-change-check-"+e+b+"0",b));else if("t"==a)for(b=1;b<=zamnum;b++)for(c in a=["time","schet","del","oops"],a)e=a[c],1==data["tchange"+b][e][0]&&($("#tac-change-check-"+e+b+"0").prop("checked","").button("refresh"),changeTac("tac-change-check-"+e+
b,"tac-change-check-"+e+b+"0",b));else if("x"==a){$("#tactic-"+a).toggleClass("active norm");for(b=1;5>=b;b++)b!=curtactic&&(data["tactic"+b]=jQuery.extend(!0,{},data["tactic"+curtactic]),data["sostav"+b]=jQuery.extend(!0,[],data["sostav"+curtactic]));$("#tactic-"+a).toggleClass("active norm")}else if("y"==a){$("#tactic-"+a).toggleClass("active norm");for(c=1;11>=c;c++)for(e=data["sostav"+curtactic][c].stda,d=data["sostav"+curtactic][c].stdo,b=1;5>=b;b++)b!=curtactic&&(data["sostav"+b][c].stda=e,
data["sostav"+b][c].stdo=d);$("#tactic-"+a).toggleClass("active norm")}else"z"==a&&($("#tactic-"+a).toggleClass("active norm"),1!=curtactic&&(b=data.tactic1,c=data.sostav1,delete data.tactic1,delete data.sostav1,data.tactic1=jQuery.extend(!0,{},data["tactic"+curtactic]),data.sostav1=jQuery.extend(!0,[],data["sostav"+curtactic]),data["tactic"+curtactic]=b,data["sostav"+curtactic]=c,$("#tactic-1").prop("checked","true").parent().buttonset("refresh"),setTactic(1)),$("#tactic-"+a).toggleClass("active norm"));
return!1}function plInfo(a,b){$("#"+b).blur();changePlData(sel,a.split("-")[1],parseInt(b.replace(a,""),10))}
function plFilterPlayer(a,b){var c="   GK DF DF DM DM AM AM FW".split(" ");return 0==a||1==a&&1!=b.school||2==a&&1==b.school||void 0!=b.position&&((3==a||10==a)&&-1<b.position.indexOf(c[a])||4==a&&(-1<b.position.indexOf(c[a])&&-1<b.position.indexOf("C")||-1<b.position.indexOf("SW"))||5==a&&-1<b.position.indexOf(c[a])&&(-1<b.position.indexOf("L")||-1<b.position.indexOf("R"))||(6==a||8==a)&&-1<b.position.indexOf("C")&&(-1<b.position.indexOf(c[a])||-1<b.position.indexOf("MF"))||(7==a||9==a)&&(-1<b.position.indexOf("L")||
-1<b.position.indexOf("R"))&&(-1<b.position.indexOf(c[a])||-1<b.position.indexOf("MF"))||9==a&&-1<b.position.indexOf("FW")&&(-1<b.position.indexOf("L")||-1<b.position.indexOf("R")))?!0:!1}
function plFilter(a){var b,c,e;curfl=a;$("#plist td.marked").removeClass("marked");cursk=getlocalStorage("sostavfilter"+a,"#");for(b in data.players)e=data.players[b],plFilterPlayer(a,e)?18<e.sos?$("tr#plsos"+e.sos).show():$("tr#plsos"+e.sos).removeClass("filtered"):18<e.sos?$("tr#plsos"+e.sos).hide():$("tr#plsos"+e.sos).addClass("filtered");a=cursk.split("#");for(c in a)""!=a[c]&&$("."+a[c]).addClass("marked")}
function skFilter(a){-1<cursk.indexOf("#"+a+"#")?(cursk=cursk.replace(a+"#",""),$("td."+a).removeClass("marked")):(cursk+=a+"#",$("td."+a).addClass("marked"));savelocalStorage("sostavfilter"+curfl,cursk)}function getlocalStorage(a,b){var c=b;void 0!=localStorage&&"undefined"!=String(localStorage[a])&&(c=localStorage[a]);return c}function savelocalStorage(a,b){void 0!=localStorage&&("#"==b?delete localStorage[a]:localStorage[a]=b)};